#cloud-config
package_update: true
packages:
  - nodejs
  - git
runcmd:
  - sleep 10
  - git clone https://github.com/YanivYuzis/fred.git
  - /bin/bash ./fred/config.sh
final_message: "System is up after $UPTIME seconds"
