#cloud-config
package_update: true
packages:
#  - nodejs
#  - nginx
  - git
runcmd:
#  - wget -q https://raw.githubusercontent.com/YanivYuzis/fred/main/index.html -O /var/www/html/index.nginx-debian1.html && systemctl start nginx
#  - busybox wget -q https://raw.githubusercontent.com/YanivYuzis/fred/main/index.html -O /var/www/html/index.nginx-debian.html && systemctl start nginx
  - git clone https://github.com/YanivYuzis/fred.git
  - /bin/bash ./fred/config.sh
#  - systemctl start nginx
final_message: "System is up after $UPTIME seconds"